id: PF0F71F95
initial_creation_type: ocr
source_metadata:
  volumes:
    ea1f3f67894e405ebf3eb31b14b570a8:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: དེ་ཁོ་ན་ཉིད་སྒྲོན་མ།
      total_pages: 1853
      volume_number: 25
