id: PF0F71F95
initial_creation_type: ocr
source_metadata:
  volumes:
    8be31dd60ccd4511a76dcfc0f504b260:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: དེ་ཁོ་ན་ཉིད་སྒྲོན་མ།
      total_pages: 1853
      volume_number: 25
