id: DA6C8E767
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:49:00+00:00'
last_modified: '2022-05-26T10:55:19.373550+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    3aaa:
      image_group_id: I1PD95870
      title: དེ་ཁོ་ན་ཉིད་སྒྲོན་མ།
      total_pages: 1853
      order: 25
      base_file: 3aaa.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
